"""empty message

Revision ID: 2bd37a009cdd
Revises: 310ca49d36da
Create Date: 2022-05-04 21:03:08.230591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bd37a009cdd'
down_revision = '310ca49d36da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postalcodes')
    op.drop_table('goals')
    op.drop_table('projects')
    op.drop_table('tasks')
    with op.batch_alter_table('a1C', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bill_dates', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'payees', ['payeefk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budget', ['budget'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('budget_income', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'budget', ['budget'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cemeteries', ['cemeteriesfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hosptial', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mileage', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'mileage_catagory', ['catagoryfk'], ['id'])

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicles', ['vehiclefk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mileage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hosptial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budget_income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bill_dates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('a1C', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('tasks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('duedate', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('goalfk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pictureurl', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_reviewed', mysql.DATETIME(), nullable=True),
    sa.Column('when_review', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notionid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('next_review', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('goals',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pictureurl', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('measurement', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('datestart', mysql.DATETIME(), nullable=True),
    sa.Column('dateend', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('postalcodes',
    sa.Column('zip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('primary_city', mysql.VARCHAR(length=27), nullable=False),
    sa.Column('acceptable_cities', mysql.VARCHAR(length=282), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('county', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('timezone', mysql.VARCHAR(length=28), nullable=True),
    sa.Column('area_codes', mysql.VARCHAR(length=39), nullable=True),
    sa.PrimaryKeyConstraint('zip'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
