"""empty message

Revision ID: 310ca49d36da
Revises: 682283259a71
Create Date: 2022-03-02 01:08:49.943392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310ca49d36da'
down_revision = '682283259a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('a1C', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bill_dates', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'payees', ['payeefk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budget', ['budget'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('budget_income', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'budget', ['budget'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cemeteries', ['cemeteriesfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hosptial', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mileage', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'mileage_catagory', ['catagoryfk'], ['id'])

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicles', ['vehiclefk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'goals', ['goalfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mileage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hosptial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budget_income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bill_dates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('a1C', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
