"""empty message

Revision ID: 4f19d7b59c1c
Revises: 2bd37a009cdd
Create Date: 2022-05-04 21:35:33.385064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f19d7b59c1c'
down_revision = '2bd37a009cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=100), nullable=True),
    sa.Column('goal_description', sa.Text(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('review_howOften', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projectfk', sa.Integer(), nullable=True),
    sa.Column('goalfk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goalfk'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['projectfk'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('a1C', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bill_dates', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'payees', ['payeefk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'budget', ['budget'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('budget_income', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'budget', ['budget'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cemeteries', ['cemeteriesfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hosptial', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mileage', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'mileage_catagory', ['catagoryfk'], ['id'])

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'budgetcats', ['catagory'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicles', ['vehiclefk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facility', ['facilityfk'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'doctor', ['doctorfk'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dish', ['dishfk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mileage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hosptial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budget_income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bill_dates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('a1C', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('goals')
    # ### end Alembic commands ###
